services:
  greenSpotFrontendBuild:
    image: node:22.4.0
    container_name: greenSpotFrontend
    ports:
      - "${SERVICE_PORT}:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "npm install && npm run dev"

networks:
  greenspot-net: