export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const MEMBER_JOIN = "MEMBER_JOIN";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_WALLET_SUCCESS = "GET_WALLET_SUCCESS";
export const GET_WALLET_FAIL = "GET_WALLET_FAIL";

export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAIL = "GET_TRANSACTIONS_FAIL";

export const GET_RESOURCES_SUCCESS = "GET_RESOURCES_SUCCESS";
export const GET_RESOURCES_FAIL = "GET_RESOURCES_FAIL";

export const GET_CPU_NAMES_SUCCESS = "GET_CPU_NAMES_SUCCESS";
export const GET_CPU_NAMES_FAIL = "GET_CPU_NAMES_FAIL";
export const GET_GPU_NAMES_SUCCESS = "GET_GPU_NAMES_SUCCESS";
export const GET_GPU_NAMES_FAIL = "GET_GPU_NAMES_FAIL";

export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";

export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_FAIL = "GET_TASKS_FAIL";

export const GET_ANALYTICS_SUCCESS = "GET_ANALYTICS_SUCCESS";
export const GET_ANALYTICS_FAIL = "GET_ANALYTICS_FAIL";

export const GET_REWARDS_SUCCESS = "GET_REWARDS_SUCCESS";
export const GET_REWARDS_FAIL = "GET_REWARDS_FAIL";
export const LOAD_REWARD = "LOAD_REWARD";

export const GET_REDEEMS_SUCCESS = "GET_REDEEMS_SUCCESS";
export const GET_REDEEMS_FAIL = "GET_REDEEMS_FAIL";

export const GET_EMAIL_NOTIFICATIONS_SUCCESS = "GET_EMAIL_NOTIFICATIONS_SUCCESS";
export const GET_EMAIL_NOTIFICATIONS_FAIL = "GET_EMAIL_NOTIFICATIONS_FAIL";
export const GET_POPUP_NOTIFICATIONS_SUCCESS = "GET_POPUP_NOTIFICATIONS_SUCCESS";
export const GET_POPUP_NOTIFICATIONS_FAIL = "GET_POPUP_NOTIFICATIONS_FAIL";

export const GET_ENABLED_PROFILES_SUCCESS = "GET_ENABLED_PROFILES_SUCCESS";
export const GET_PROFILES_FAIL = "GET_PROFILES_FAIL";
export const GET_DISABLED_PROFILES_SUCCESS = "GET_DISABLED_PROFILES_SUCCESS";


export const GET_ASSIGNMENT_SETTINGS_SUCCESS = "GET_ASSIGNMENT_SETTINGS_SUCCESS";